definitions:
  generated.Order:
    properties:
      bonusid:
        type: integer
      comment:
        type: string
      customerid:
        type: integer
      deliveryagentid:
        type: integer
      feeid:
        type: integer
      id:
        type: integer
      paymentid:
        type: integer
      restaurantid:
        type: integer
      status:
        type: string
      timestamp:
        type: string
      totalamount:
        type: number
      vatamount:
        type: number
    type: object
  handlers.UpdateOrderStatusRequest:
    properties:
      status:
        example: Pending/On its way/Delivered
        type: string
    type: object
info:
  contact: {}
paths:
  /api/order/consume:
    get:
      description: Consume the created order for customer
      produces:
      - application/json
      responses:
        "200":
          description: Order Consumed Successfully
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Consume Order for a Customer
      tags:
      - order
  /api/order/status/{orderId}:
    patch:
      consumes:
      - application/json
      description: Updates the status of an order
      parameters:
      - description: Order ID
        in: path
        name: orderId
        required: true
        type: integer
      - description: New Order Status
        in: body
        name: status
        required: true
        schema:
          $ref: '#/definitions/handlers.UpdateOrderStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Order status updated successfully
          schema:
            type: string
        "404":
          description: Order not found
          schema:
            type: string
      summary: Update Order Status
      tags:
      - orders
  /api/orders:
    get:
      description: Fetches a list of all orders from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/generated.Order'
            type: array
      summary: Get all orders
      tags:
      - orders
  /api/orders/{id}:
    delete:
      description: Deletes an order by its id from the database
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Order deleted successfully
          schema:
            type: string
        "404":
          description: Order not found
          schema:
            type: string
      summary: Delete an order
      tags:
      - orders
    get:
      description: Fetches an order based on the id from the database
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/generated.Order'
      summary: Get order by id
      tags:
      - orders
swagger: "2.0"
