definitions:
  generated.CreateCustomerParams:
    properties:
      address:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phonenumber:
        type: string
    type: object
  generated.Customer:
    properties:
      address:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      phonenumber:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/customer:
    get:
      description: Fetches a list of all customers from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/generated.Customer'
            type: array
      summary: Get all customers
      tags:
      - customers
    post:
      consumes:
      - application/json
      description: Creates a new customer entry in the database
      parameters:
      - description: Customer object
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/generated.CreateCustomerParams'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/generated.Customer'
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create a new customer
      tags:
      - customers
  /api/customer/{id}:
    delete:
      description: Deletes a customer based on the id from the database
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Customer deleted
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Customer not found
          schema:
            type: string
      summary: Delete customer
      tags:
      - customers
    get:
      description: Fetches a customer based on the id from the database
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/generated.Customer'
      summary: Get customer
      tags:
      - customers
swagger: "2.0"
