version: "3.8"

services:
   redis:
      container_name: ${CONTAINER_NAME}
      image: redis:alpine
      environment:
         - REDIS_PASSWORD=${REDIS_PASSWORD} # rest of variables in .env
      command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
      ports:
         - "${REDIS_PORT}:6379"
      networks:
         - db
      restart: unless-stopped
      healthcheck:
         test: ["CMD-SHELL", "redis-cli -h localhost -p 6379 ping"]
         interval: 30s
         timeout: 10s
         retries: 5

   go-api:
      container_name: go-api
      build:
         context: ./
         dockerfile: Dockerfile
      ports:
         - "8084:8084"
      depends_on:
         redis:
            condition: service_healthy
      networks:
         - db
      restart: on-failure
      profiles:
         - api
         - app

networks:
   db:
      driver: bridge
