version: "3.8"

services:
  redis:
    container_name: ${CONTAINER_NAME}
    image: redis:alpine
    environment:
      - REDIS_PASSWORD=${DB_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h localhost -p 6379 ping"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  db:
    driver: bridge
