basePath: "8083"
definitions:
  generated.Menuitem:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      restaurantid:
        type: integer
    type: object
  generated.Restaurant:
    properties:
      address:
        type: string
      category:
        type: string
      id:
        type: integer
      name:
        type: string
      rating:
        type: number
      zip_code:
        type: integer
    type: object
  handlers.MenuItemSelection:
    properties:
      customerId:
        example: 1
        type: integer
      name:
        example: Cheese Burger
        type: string
      price:
        example: 10
        type: number
      quantity:
        example: 2
        type: integer
      restaurantId:
        example: 10
        type: integer
    type: object
  handlers.SelectItemParams:
    properties:
      customerId:
        example: 1
        type: integer
      id:
        type: integer
      quantity:
        example: 2
        type: integer
      restaurantId:
        example: 10
        type: integer
    type: object
host: 'localhost:'
info:
  contact:
    email: support@example.com
    name: API Support
  description: This is the API documentation for the Restaurant Service.
  title: Restaurant Service API
  version: "1.0"
paths:
  /api/categories:
    get:
      description: Fetches a list of all unique categories from the restaurant
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get all categories
      tags:
      - categories
  /api/filter/{category}:
    get:
      description: Fetches all restaurants for a given category
      parameters:
      - description: Restaurant Category
        in: path
        name: category
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/generated.Restaurant'
            type: array
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Filter restaurants by category
      tags:
      - categories
  /api/restaurants:
    get:
      description: Fetches a list of all restaurants from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/generated.Restaurant'
            type: array
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get all restaurants
      tags:
      - restaurants
  /api/restaurants/{id}:
    get:
      description: Fetches a restaurant based on the id from the database
      parameters:
      - description: Restaurant ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/generated.Restaurant'
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get restaurant by id
      tags:
      - restaurants
  /api/restaurants/{restaurantId}/menu-items:
    get:
      description: Fetches all menu items associated with a specific restaurant ID
      parameters:
      - description: Restaurant ID
        in: path
        name: restaurantId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/generated.Menuitem'
            type: array
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get menu items by restaurant ID
      tags:
      - menu_items
  /api/restaurants/{restaurantId}/menu-items/{menuitemId}:
    get:
      description: Fetches a menu item based on the restaurant and id from the database
      parameters:
      - description: Restaurant ID
        in: path
        name: restaurantId
        required: true
        type: string
      - description: Menu Item ID
        in: path
        name: menuitemId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/generated.Menuitem'
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get menu item by restaurant and id
      tags:
      - menu_items
  /api/restaurants/menu/select:
    post:
      consumes:
      - application/json
      description: Select Menu Item
      parameters:
      - description: Menu item selection details
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/handlers.SelectItemParams'
      produces:
      - application/json
      responses:
        "201":
          description: Menu item successfully selected
          schema:
            $ref: '#/definitions/handlers.MenuItemSelection'
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Select MenuItem
      tags:
      - BrokerCustomers
swagger: "2.0"
