global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "customer_service"
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: "order_service"
    static_configs:
      - targets: ["host.docker.internal:8082"]

  - job_name: "restaurant_service"
    static_configs:
      - targets: ["host.docker.internal:8083"]

  - job_name: "shopping_cart_service"
    static_configs:
      - targets: ["host.docker.internal:8084"]
