definitions:
  db.AddItemParams:
    properties:
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
      user_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/shopping:
    post:
      consumes:
      - application/json
      description: Add an item to the shopping cart
      parameters:
      - description: item object
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/db.AddItemParams'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/db.AddItemParams'
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Add an item
      tags:
      - shoppingCart
swagger: "2.0"
