definitions:
  db.AddItemParams:
    properties:
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
      user_id:
        type: string
    type: object
  handlers.UpdateQuantityRequest:
    properties:
      quantity:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/shopping:
    post:
      consumes:
      - application/json
      description: Add an item to the shopping cart
      parameters:
      - description: item object
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/db.AddItemParams'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/db.AddItemParams'
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Add an item
      tags:
      - shoppingCart
  /api/shopping/{userId}/{itemId}:
    patch:
      consumes:
      - application/json
      description: Update the quantity of an existing item in the shopping cart. If
        the quantity is set to 0, the item will be removed.
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      - description: Item ID
        in: path
        name: itemId
        required: true
        type: string
      - description: New quantity for the item
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.UpdateQuantityRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Item updated successfully
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "404":
          description: Item not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update an item in the cart
      tags:
      - shoppingCart
swagger: "2.0"
