name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: "Run CI for ${{ matrix.service }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - customerService
          - orderService
          - restaurantService
          - shoppingCartService
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          check-latest: true

      - name: Run Tests
        working-directory: services/${{ matrix.service }}
        run: go test ./...

      - name: Run Go Vet
        working-directory: services/${{ matrix.service }}
        run: go vet ./...

      - name: Install Staticcheck and Run
        working-directory: services/${{ matrix.service }}
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...
