name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  ci:
    name: "Run CI for ${{ matrix.service }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          [
            customerService,
            orderService,
            restaurantService,
            shoppingCartService,
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          check-latest: true

      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run Tests, Vet, and Staticcheck
        working-directory: services/${{ matrix.service }}
        run: |
          go test ./...
          go vet ./...
          staticcheck ./...

      - name: Set Lowercase Service Name
        id: set-lowercase
        run: echo "service_name=$(echo ${{ matrix.service }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: . #services/${{ matrix.service }}
          file: services/${{ matrix.service }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.service_name }}:latest
