name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  filter:
    name: "Determine Changed Services"
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Filter Changed Services
        id: filter
        uses: dorny/paths-filter@v2
        with:
          base: ${{ github.ref }}
          ref: ${{ github.event.pull_request.head.sha }}
          filters: |
            customerService:
              - "services/customerService/**"
            orderService:
              - "services/orderService/**"
            restaurantService:
              - "services/restaurantService/**"
            shoppingCartService:
              - "services/shoppingCartService/**"
          write_outputs: "json"

      - name: Set matrix output
        id: set-matrix
        run: |
          echo "matrix=$(echo '${{ steps.filter.outputs.changes }}' | jq -c .)" >> $GITHUB_OUTPUT

  ci:
    name: "Run CI and Build Docker Images"
    needs: filter
    if: ${{ needs.filter.outputs.services != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.filter.outputs.services) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          check-latest: true

      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run Tests, Vet, and Staticcheck
        working-directory: services/${{ matrix.service }}
        run: |
          go test ./...
          go vet ./...
          staticcheck ./...

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: services/${{ matrix.service }}
          file: services/${{ matrix.service }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:latest
